# Create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Hudson",
    "lastName": "Bean",
    "userName": "ZombieKicker7",
    "email": "hudsonbeandev@gmail.com",
    "password": "Copsreloaded62$",
    "phoneNumber" : "3164940195"
}

###
