# Get all users
GET http://localhost:3000/users

###

# Decrypt email, phoneNumber, and password

POST http://localhost:3000/users/671b97990cff9683acc0822e/test
Content-Type: application/json

{
    "myPassword": "Copsreloaded62"
}

###

# Create user
POST http://localhost:3000/users
Content-Type: application/json

{
    "firstName": "Hudson",
    "lastName": "Bean",
    "userName": "ZombieKicker7",
    "emailAdress": "hudsonbeandev@gmail.com",
    "password": "Copsreloaded62$",
    "phoneNumber" : "3164940195"
}

###

#Get a user
GET http://localhost:3000/users/671b97990cff9683acc0822e